# Generated by Django 3.2.5 on 2021-07-30 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DongLand', '0002_auto_20210722_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowns', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=150, null=True, verbose_name='subject')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('location', models.TextField(blank=True, null=True, verbose_name='location')),
                ('amount', models.FloatField(max_length=15, verbose_name='amount')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='sina', verbose_name='picture')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_creator', to=settings.AUTH_USER_MODEL)),
                ('payers', models.ManyToManyField(related_name='expense_payers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bunch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bunch_creator', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(related_name='bunch_members', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
