# Generated by Django 3.2.5 on 2021-08-05 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DongLand', '0003_bunch_expense_friend'),
    ]

    operations = [
        migrations.AddField(
            model_name='bunch',
            name='token_str',
            field=models.CharField(default='SGVT7RHADF', max_length=10),
        ),
    ]
