# Generated by Django 3.2.5 on 2021-08-13 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DongLand', '0005_alter_bunch_token_str'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='creator',
        ),
        migrations.AddField(
            model_name='expense',
            name='bunch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_bunch', to='DongLand.bunch'),
        ),
        migrations.AddField(
            model_name='expense',
            name='main_payer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_main_payer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bunch',
            name='token_str',
            field=models.CharField(default='T8JSAEKMYL', max_length=10),
        ),
        migrations.AlterField(
            model_name='expense',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='picture'),
        ),
    ]
