# Generated by Django 3.2.5 on 2021-08-13 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DongLand', '0007_auto_20210813_0856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='payers',
        ),
        migrations.AddField(
            model_name='expense',
            name='token_str',
            field=models.CharField(default='C6P4V60OLJ', max_length=10),
        ),
        migrations.AlterField(
            model_name='bunch',
            name='token_str',
            field=models.CharField(default='UPQ0T2PNO2', max_length=10),
        ),
    ]
