# Generated by Django 3.2.5 on 2021-08-18 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DongLand', '0008_auto_20210813_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bunch',
            name='token_str',
            field=models.CharField(default='NFPDGDSP83', max_length=10),
        ),
        migrations.AlterField(
            model_name='expense',
            name='token_str',
            field=models.CharField(default='K9L7ZCFN9K', max_length=10),
        ),
    ]
