# Generated by Django 3.2.5 on 2021-08-18 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DongLand', '0009_auto_20210818_0915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='date_created',
        ),
        migrations.AddField(
            model_name='expense',
            name='date',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='bunch',
            name='token_str',
            field=models.CharField(default='2FMQ4GP4CX', max_length=10),
        ),
        migrations.AlterField(
            model_name='expense',
            name='token_str',
            field=models.CharField(default='0J5O1FCJZE', max_length=10),
        ),
    ]
