# Generated by Django 3.2.5 on 2021-08-18 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DongLand', '0010_auto_20210813_1831'),
        ('DongLand', '0010_auto_20210818_0926'),
    ]

    operations = [
    ]
