# Generated by Django 3.2.5 on 2021-08-18 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DongLand', '0012_auto_20210818_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bunch',
            name='token_str',
            field=models.CharField(default='AQDROFJPD9', max_length=10),
        ),
        migrations.AlterField(
            model_name='expense',
            name='picture',
            field=models.ImageField(blank=True, default='no_image.png', null=True, upload_to='images', verbose_name='picture'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='token_str',
            field=models.CharField(default='72QT5IKS5C', max_length=10),
        ),
    ]
