# Generated by Django 3.2.5 on 2021-08-19 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DongLand', '0014_auto_20210819_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='type_of_calculation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bunch',
            name='token_str',
            field=models.CharField(default='72NJDIRT8Q', max_length=10),
        ),
        migrations.AlterField(
            model_name='expense',
            name='token_str',
            field=models.CharField(default='IMEGE7ZGVP', max_length=10),
        ),
    ]
