# Generated by Django 3.2.5 on 2021-08-19 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DongLand', '0015_auto_20210819_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bunch',
            name='token_str',
            field=models.CharField(default='N5VNIA6N34', max_length=10),
        ),
        migrations.AlterField(
            model_name='expense',
            name='token_str',
            field=models.CharField(default='5DHOCVWZST', max_length=10),
        ),
    ]
